#本地测试环境使用
server:
  port: 8085
  tomcat:
    max-connections: 60000
    connection-timeout: 6000s
    max-http-form-post-size: 9000000
spring:
  datasource:
    url: jdbc:mysql://192.168.200.129:3306/xtx_manager?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: xc@123pawsd!!
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 301MB
  redis:
    host: 192.168.200.129
    port: 6379
    password: xc@123pawsd!!
    database: 0
  cache:
    type: redis #缓存类型
    redis:
      cache-null-values: false #不缓存null数据
      time-to-live: 50000ms #超时时间
      use-key-prefix: false #不使用前缀
  rabbitmq:
    host: 192.168.200.129
    port: 5672
    username: admin
    password: pass
    #虚拟主机 一台机器可能有很多虚拟主机 这里选择默认配置 / 即可
    virtual-host: /

elasticsearch:
  # host: 127.0.0.1
  host: 192.168.200.129
  port: 19200
  scheme: http
  connectTimeout: 100000
  socketTimeout: 100000
  connectionRequestTimeout: 100000
  maxConnectNum: 100
  maxConnectPerRoute: 100
  keepAliveMinutes: 10
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#上传临时文件夹
tmp:
  file-directory: /home/upload
token:
  # 3分钟 180000 3天 259200000L 15天1296000000
  ttlMillis: 259200000
  refreshTokenTimeout: 1296000000

#短信相关的配置信息
sms:
  region-id: cn-hangzhou
  accessKey: LTAI4FqsEN4TvQo4859WFfPr
  secret: T0FOH2W6Kv06vTJv7bCEOSe0Bh7fOY
  register:
    sign: 传智播客
    template-code: SMS_173696218
  login:
    sign: 传智播客
    template-code: SMS_173696220
  reset:
    sign: 传智播客
    template-code: SMS_173696217
  social:
    sign: 传智播客
    template-code: SMS_173696221
  testCode: 123456


pay:
  expires:
    #支付过期时间， 默认是30分钟
    pc: 15
    app: 15
  #使用沙箱环境
  ali:
    appId: 9021000137617878
    # publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwJ5jPqUBHAz1WKKdOg/xAsAamsq3MouMp8Ul6yrsn/akhS/defsyrhJUjJth/iDEN2PySyS5iirYKuGYWUJwUP73H6LRnAZbd2AmwMEgOXcNg92QVVNn7Zn2OKCzXAhnufO3zEF93OwQCPxBSJdnRa3mZ8KYu0JJfneQ1AMvPbAQnH3BtjoxhUeYIIdLUuSDfWf40Ztyu19fJvihE3giMFjF8F1JfhO5fsD0QObV9t/UUWeCKr9jNlgbynDYkUAL4jaKsvvwXeSxpm/ioODEdpsjM1OurPTUmi8Q7Mbg1MFNykO+CN0VJYHp3WBGQArA3XQhcjsUgCjS5M/uBCVClQIDAQAB
    publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkVV23xcDSBBGiZboD7DDlYIzKXK6oEmnSU/7gzAfUbm6KSjV3VbdzuAfFRrU2MwtaLeKKuJJ+e7Vf3zw+Hvq2YiPidGVP+xPUycwwuhfF50DdMTBBvgE++gXLwMIEJSpMYn5nOzZoChoxMOvHI8aVi2ZnwBchpwg3543R+OCjx0RYzUw6qHRUxCSDNVezP8UIngLoAwuq7jVnsWR5oZ6mSnAFj1BGg4UsaLccnY7FuHPPDKZ4+7Lo61fMuPxep3h7JddUaHlfi2eghUHJxEvbC8hnvRi2HfS0KbRFEI/t1EoNwSRc4QciXvO6oqX3TrYh8Grzg1Qz2vXFtrUgoH++QIDAQAB
    # privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCqQkw63HtGGyEoZ5uDGrYcqLix2nUsm5W45jsgKgH+D9MNnFNNHcmFiwT5UJCVgIRI2v0XJ/bW+PxoALrwegQgPjz0cOI1qAKY9dO7oF9gOWG1hnMgxfuVLn1xAWsVPhJYWmbFVi5Dmx46cwCaqf8oaPAMDqnF+EO0aLxGlZ1CgEEozpRFyoy/mrSHsSU2p/7v01DaMpi2YkaRVC9mZsWPt0V92GkOauWyzbW5T9RN6gmzpLOiq5we4KQMcL2JRT7Tax3Xcvzpi/RXXQPEAvwzO2zPZh1ZfswfWFjgj2+apxwzNotmJL2/KdsW9VL7OHIT7aM74mfxRSS938/JRZIbAgMBAAECggEAFn11dl0Dh6ozwhOVjkbsAXMkGpJB4ieXKnp3GvORmc7bUTPyKQCjSxmnCYvj3WvBjaInxnRH/fOb290k1Hk5rEysXpm+t9m+phfq5SD1GE/cIU9mS9D7P6SJe3D1hTPS1orygmS07cdCwfPJA6UrCFp8Qwt4z6bQwrcHD8fZoxv4wApgmaV75aiSxI04k1vLruLzyowxRXcrCVfYiaIGTrhPlbSXcSXOF83IelTzNYDunxSX7g00JSOrKG4xuEfoKYIHiguL8SKm6XxXAY2zxh2JSwS/Ce2W8/Au1FMDcETNsrWrmoO7FckKOIkyQY6W+7OBwffaFfyzxg0k00UTiQKBgQDdLPryPOjL43N7zpUU9jgogSau2dE9HvkpqFmscnAskQkvUpquWWREbuG0RfANin6ClMxrXYpNxhrFQx3C9IXMp08u4o+pULXLVrMUfoJuoz75wxffcyoW4Gwf/T5TCO3dbKJvEoSvEDJP8WU0FFhgTPdTVzf8nDle3w0WajrnJwKBgQDFEP7+zLOThdH766XGIOcZGIORTvO95aTF9HSsuSiazmaxLpPWRoKWGVAn4+F9h/KbQh4C73y8Mc2jhbahUgQgmhv2K3lufKMtdrwx/OIhCmcZ/fZakGhCG8mwjHDKJTBy3Ytv3Etn+VXgUzV9iauutEm/xwvxvTuCISeCU5m17QKBgBxVwuB9xSU5wnW+BYNl99PYl+gWp6O48BrSIorhLlXHTvHtFzv2382Ulv3NZ++UKpj4DyhCF5HXK17SNmHfibSqSo6rH9SFLoUaWl7pxjP+XfcJc2mBC4dawP9oJi/lGPQhEr5AFReIb6mmN1zwrlHICnd22QlXylHJKZgRi/JJAoGAKqUA6VaWzae5xxA5cWSRXebmIb26FS/qtkOuM+pllQpxQopXx5i+jYiwxdEUbLvMjjiCkhQNJBSK8YXv/XzoE74FqwHBZ11lWmNFWnPk402C/ibs9rAlP5kPzjq19aiSkWjL0csULk3QfZjEDISMOGQfSXbjaM6QYBqYmCVLMAkCgYEAnBeq+qctChFZLogpVmnmTfFkdESlPQqN0KZ6+TiwQxCLrv1HKRXPGLjebzly3VVR4areTpzSzQ/yPX5Mle+GhPJzH69+3ShqNVGCQyFzAoFXKnkPjRKWnqiFFbVWzZwApt3Zkmt2AMpXiX68r/q8qKm78wkva1uZCc4GRmCOWfo=
    privateKey: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCnbM7Nqc+B8edNCgecDFqssKhk2u90AHVrNj755nkiBg6AtX+0bNhxI6X0XV+5Yh5YbGfWqyQguW2sZ2vTZuaQl79+ENYSI2utZSColgdB+uozb63GtdRg9BCvilwCbHmwpzLo0BxBE2M53QRBpSKW0BcgVIHt39qAc4z6hWHL5RjgdDPNvej8XZupCx590FYgwLX5By6LoMmgAThziEOzw1DlZZuyNC1PR/whmVIuFi6oc6jFlFA2MFvEpAj6Ih6Yfi6H3PmWB5RmR3vUFZo9x3lkMCQQAq7FDZFJp1nrWn3ccswGFTtw+Y78OF3VXeASoHfNIMOHhCOxoxjFOzk9AgMBAAECggEAb9CqWQ506KsfOANfy6cwk66z+A+D5mw7/ytOaeWztrZmzyzoKh6beww81HPb71qJO7LCssq/qR9OENtNVvWdPKosGMyzu49uZXJpmk4AcN9btJh8bX6YZVv7HNGB25iIuSMhS/1ZMVj6ZvWl1xWrgR9eopft4mkja7BAUjvscZftgkM6uaydCZOfeMVbnGEanr0c0toYzb7sl9ZFocjIqdmcOEBXzFTfpT0pmMG+SnhOX1xGnsGr1iGntCsxFgSAVwpqNB/ezg9E9u6XQS5RBatLxiK+4Y21f2nZv4NYqzTd31uoOXJVL3jp4y1dvJugOK9uhXqY97AZg9VcxlX4XQKBgQDefJGqU3hmuG3W/HUlfyQz2VBGUdV6GPjvMnsayztL6SY6s/1gD6dgq/tyWPdZFRu1z2rsFKMciEhXj8b8Lef9rEZ5D1uJ6XYZjR4dH5XiTuhOpLuqLkLfOU/ufbiOjri0vhsLwBO9RoMsGgCU2Y8Cq3NFaVkLNGRc/0Sbq9FpTwKBgQDApPqNeRUL8PXczettswBLJupD5FVDJOVzpY6Zj1jMMKzU3JnQTc0wnj2l3V1yenJXEQoPHRAjlxZAu1j7CJENfVL5lu5cSRKJE9QcDu5a2R4sqe2TxeqzSId2a0GGndsLt+/1ieb+YWgE8DN8lemW5JKpgj2PkWcXKQm0meQ5swKBgFXu5VBVVx7Nw1cTQagO+IuyNwhCGWNEe/nflJ7funJyhhqMZKQSx8JWCxO6eycEOSS7DYBL5Ehj9xUi6meCz6UyQjIGFYQqETyDPgtfpMO5WI7vn7B2l8uiVlY2Zu9g/sSI3Odn8/faYVXKYUkc0tjkIezAaO0j+lPVIMnDzmmPAoGAFt8/lC5tDkbkmfuk2Rhoj4OmSrtAWEF4MJvWa2r2iv+4dWlfpbinBP+0qA25O49IJggy3op/0QnuLW9Q6DUjK6vWfyWpVTGjzryY8V/gcs7WY00llObpr7GLy8Z+OCJj0GddSRS/ZTJhbDyskD0oR68JrrB06KfFyp0nttaSnzsCgYBkTlR2QS17DYa+ySrwqKzMJINXE+MSQbrJByg6DrXv4ywsonpZugZPYOxi/l7u5BbS5HMWsgoGiywawuZg1RlJRdMHYezkWd00PLVzPumcO1bPFJomNVQI6atISm6U7v19Rlg2re0j8zJcCBDfg1OP8npFK5tjJPRvIt3PXyDtJA==
    serviceUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    #同步回调地址
    returnUrl: http://127.0.0.1:8085/pay/returnUrl
    #异步回调
    #内网穿透
    notifyUrl: http://89zzwniz.beesnat.com/pay/notifyUrl
    #重定向页面（支付成功或者失败的页面）
    #    redirectUrl: http://erabbit.itheima.net/#/pay/callback
    redirectUrl: http://127.0.0.1:5173/paycallback
    #网关
    gatewayurl: https://openapi-sandbox.dl.alipaydev.com/gateway.do

  #PC微信支付
  wx:
    #应用编号
    appid: wxffb3637a228223b8
    #appSecret 是 appId 对应的接口密码，微信公众号授权获取用户 openId 时使用
    appSecret: 12
    #微信支付商户号
    mchId: 1561414331
    #API 私钥字符串
    privateKey: -----BEGIN PRIVATE KEY-----MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQChXKhMDNcjxTBOFF2NOHai5NwChO12f3KQbmqCNEXWImqC5OtTEmcy/8Kzx8i243TtkVFv+Eqvac69/gpytl8sK8GFCzzUExgtejrtr3cJS//0eaJURGVG9zDPHrGV5vtXqmUPzAzX5SbMsIEKAZoe2bRJRz5zNNx+RMReSOC7F4xn+5tQd3XmZomwFGKO0oryKEocw5IGdYL61zRkUK9yRtyDZKq7hvPv11YQgnD8+EeGgo5/0kk62sbWW545Hw1qVqkQjkOfbdtLQjz4BnbakUwdRn3qoCjga8QQp0EKaGbIu4haHReyP8QQZhq0KlRX6XjBbrk8k4yKURVkjrxVAgMBAAECggEAT7HjrSvqVdBeOzHzwnvQnENMJjJg1dW8T3k5QXVvyILW+C73yt+b+KQ5FXHmv+03It5Sympm+JvZcBy4LE/GUZqKyZrzQAruNgfYcuvmbsEKeURZ2CSvoI0VnjYan16lZHbT0ymEblzO/Olv0fFYnUQItuho/51sCTENi0OTOtNtrWahbOnrBk+WsgmhNen+W/KdFXA9EOFKoFclAPEpCUa/mi1/w7AQecHZUISeRXixSZbhHIF4bf7BDXqkgtnWEkBX2hZP61TibGiRUgHvVC6V5+bi07cv7jr6IjJdNvwKMjAw2GgwZvyb8HvcQ0M7ULmYC6ZXYfVuvZDXJuMCAQKBgQDTAltDJ3oE1tJtk3qgichuWf8OKlvNmN2fxiDG+rxOgTi2gL9N3BKIYWQRo3f2B9C243Z1iM+Q/4LPii6FiLTSPQYRcNaryB1BtNGjexHMK5NuCfZ2etx3zmYz86YiWY6ZsFuISFttdPq01MKRxN/gIfiXvRlv4g1SIK6vy3lpjQKBgQDDxF/Q2xNFZq8WZ4M1DW3r9EcnYgn6U8qKfDJFvW4VT9bHOJOxxmZ3oIccSuPky7gm9DlxRC632z1FyPu6buC7pp7X8+JJPmkq2c0fKYl5B5boJdBCs8QrRQ89oORFuB3/2on9N6YCMccf1VQ3kspm5GhEkO/mdN7uNYBRq1oX6QKBgAT77UPszskGefn0ndTk7EMPBSNEhN6aWcHIYEXS7le8XaaR6/Le2+E0y7RO9CpvjNKFFOs5zA1Uu7ZDQU4OKJc+scH/tFJia659ouYFpin4bYcP3S53QHXj/i4D90ygaOngbIkPjHlNZg6XZ/EhgVg99S1AXjVyVXY3J2knmTqRAoGAfuhtyOJMMuBnPpnqB9ll2eFowxIeL8Zj9bSfjnBHzc8NB+cYb9WTFZfeHqw54ldiUPZfypqNwqiApx2semZoj51rOcmjdyHbYWkCPWJa+Te/T008HhGVaQuC3svPT5cU84jDjYCmwKNuV6eeycwCJAOLyG9A5d/7qObMAaWYaQkCgYBge3oRaGlDujnn0UDwLppiytsr4TDuDvkaRLCx4OrT86Yr+gWGjo46pBYIPJ8yy59yRTVYTpDiOLLC51qweh2wKo6+/qtzNwp41jadphbpEgGRE+mpvUWtlj4yPkojSY83Gh36eWVGISDG95z1DDjjsGT8hwQgcQJHrQhWn/cltQ==-----END PRIVATE KEY-----
    #API V3密钥
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    # 商户证书序列号
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    #外网访问项目的域名，支付通知 中会使用
    domain: api.mch.weixin.qq.com
    notifyUrl:  http://www.eehp.cn
    refundNotifyUrl: http://www.eehp.cn/#/pay/callback
  # 微信小程序
  wxApp:
    #应用编号 #使用公司主体申请的
    # appId: wx26729f20b9efae3a
    appId: wxf7f8aa4c7e3d366e # 测试账号
    #appSecret 是 appId 对应的接口密码，微信公众号授权获取用户 openId 时使用 #使用公司主体申请的
    appSecret: 8e36ef64b26e533ad91f7e9a8088655e #测试账号 wxf7f8aa4c7e3d366e
    # appSecret: b55779383972332e1c69cc05a5fb4489
    #微信支付商户号 #临时使用需要更换
    mchId: 1607048370
    #API 密钥
    partnerKey: f023175a3fd892cea46271e357c5969b
    #apiclient_cert.p1 证书路径，在微信商户后台下载
    certPath: 12
    #外网访问项目的域名，支付通知 中会使用
    domain: http://pcapi-xiaotuxian-front.itheima.net
    notifyUrl: http://pcapi-xiaotuxian-front.itheima.net
    refundNotifyUrl: http://erabbit.itheima.net/#/pay/callback
    #微信提供的接口地址
    seesionHost: https://api.weixin.qq.com/sns/jscode2session
    grantType: authorization_code
  wx-mini:
    #应用编号
    appId: wx26729f20b9efae3a
    #appSecret 是 appId 对应的接口密码，微信公众号授权获取用户 openId 时使用
    appSecret: b55779383972332e1c69cc05a5fb4489
    #微信支付商户号
    mchId: 1473426802
    #API 密钥
    partnerKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    #apiclient_cert.p1 证书路径，在微信商户后台下载
    certPath: 12
    #外网访问项目的域名，支付通知 中会使用   http://fvhyez.natappfree.cc-内网穿透的地址
    domain: http://fvhyez.natappfree.cc
    notifyUrl: http://d8wbvd.natappfree.cc/pay/wxMiniPayNotice
    refundNotifyUrl: http://d8wbvd.natappfree.cc/pay/wxMiniPayNotice

itheima:
  swagger:
    swagger-path: com.itheima.xiaotuxian
    title: 店铺模块
    description: xtx-pc-manager
    contact-name: 上海黑马
    contact-url: www.itheima.com
    contact-email: itheima@itcast.cn
